---
- name: Deploy stack 
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    palo_role: pan-Transit
    palo_node_ip: eu-west-1
    vpn_connection_id: "mghali"
    vpn_bucket_name: "stack-deploy"
    
  tasks:
  # Basic task example
    - name: Configure VPN Connection 
      command: "python ../scripts/configure-vpn-v2.py {{palo_role}} {{palo_node_ip}} {{palo_node_key}} {{vpn_connection_id}} {{ vpn_bucket_name }}"
      register: outputs
    
    - name: get outputs
      debug:
        msg: "{{ outputs }}"