---
- name: Deploy stack 
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    stackname: pan-transit
    region: eu-west-1
    owner: mghali
    keyname: pan-key.pem
    Email_notification: test@example.org

  tasks:
  # Basic task example
    - name: launch ansible cloudformation example
      cloudformation:
        stack_name: "ansible-cloudformation-{{ stackname }}"
        state: "present"
        region: "{{ region }}"
        #disable_rollback: true
        template: "../files/prerequest.yml"
        template_parameters:
          paBootstrapBucketname: "pan-Bootstrap"
        tags:
          Stack: "ansible-cloudformation"