---
- name: Deploy stack 
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    stackname: pan-Transit
    region: eu-west-1
    owner: "mghali"
    keyname: "stack-deploy"
    Email_notification: "test@example.org"
    TerminationProtection: "No"
    BgpAsn: "64115"
    VpcCidr: "10.100.1.0/16"
    Gateway1: "10.100.1.1"
    Gateway2: "10.100.2.1"
    Mgmt1PrivIp: "10.100.2.100"
    Mgmt2PrivIp: "10.100.4.100"
    PubSubnet11: "10.100.1.0/24"
    PubSubnet12: "10.100.2.0/24"
    PubSubnet21: "10.100.3.0/24"
    PubSubnet22: "10.100.4.0/24"
    PAVMType: "t2.micro"
    LicenseModel: "LicenseIncluded"
    AccountId: "321726395275" 

  tasks:
  # Basic task example
    - name: Create bootstrap bucket for PAN VMs
      cloudformation:
        stack_name: "ansible-cloudformation-vm-bootstap-bucket-{{ stackname }}"
        state: "present"
        region: "{{ region }}"
        #disable_rollback: true
        template: "../files/prerequest.yml"
        template_parameters:
          paBootstrapBucketname: "{{ pan_bootstrap }}"
        tags:
          Stack: "ansible-cloudformation"
    
    #- name: upload pootstraping files to paBootstrapBucket 
    #  command: "sed -i -e 's/172.15.15.15/XYZ/g' ../files/bootstrap/config/bootstrap.xml"

    - name: upload pootstraping files to paBootstrapBucket 
      command: "aws s3 cp --region {{ region }} --recursive ../files/bootstrap  s3://{{ pan_bootstrap }}/"

    - name: launch Transit VPC cloudformation template
      cloudformation:
        stack_name: "ansible-cloudformation-VPC-{{ stackname }}"
        state: "present"
        region: "{{ region }}"
        #disable_rollback: true
        template: "../files/pan-transit-vpc-v3.json"
        template_parameters:
          KeyName: "{{ keyname }}"
          paBootstrapBucketName: "{{ pan_bootstrap }}"
          TerminationProtection: "{{ TerminationProtection }}"
          BgpAsn: "{{ BgpAsn }}"
          VpcCidr: "{{ VpcCidr }}"
          PubSubnet11: "{{ PubSubnet11 }}"
          PubSubnet12: "{{ PubSubnet12 }}"
          PubSubnet21: "{{ PubSubnet21 }}"
          PubSubnet22: "{{ PubSubnet22 }}"
          Mgmt1PrivIp: "{{ Mgmt1PrivIp }}"
          Mgmt2PrivIp: "{{ Mgmt2PrivIp }}"
          PAVMType: "{{ PAVMType }}"
          LicenseModel: "{{ LicenseModel }}"
          AccountId: "{{ AccountId }}"
        tags:
          Stack: "pan-Transit-VPC-cloudformation-template"
    - name: get outputs
      cloudformation_facts:
        stack_name: "ansible-cloudformation-vm-bootstap-bucket-{{ stackname }}"
        region: "{{ region }}"
      register: my_stack
    - name: get outputs
      debug:
        msg: "{{ my_stack.ansible_facts.cloudformation[stack_name].stack_outputs }}"
    #- name: Configure PALo PAVM1 
    #  command: "python ../scripts/configure-network.py {{ palo_node_ip }}  {{ keyname }}  {{ Gateway1 }}  {{ Mgmt1PrivIp }}"