---
- name: Deploy stack 
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    stackname: pan-Transit
    region: eu-west-1
    owner: "mghali"
    keyname: "pan-key.pem"
    Email_notification: "test@example.org"
    TerminationProtection: "Yes"
    BgpAsn: "64115"
    VpcCidr: "10.100.1.0/16"
    PubSubnet11: "10.100.1.0/24"
    PubSubnet12: "10.100.2.0/24"
    PubSubnet21: "10.100.3.0/24"
    PubSubnet22: "10.100.4.0/24"
    PAVMType: "t2.micro"
    LicenseModel: "PYEG"
    AccountId: "321726395275" 

  tasks:
  # Basic task example
    - name: Create bootstrap bucket for PAN VMs
      cloudformation:
        stack_name: "ansible-cloudformation-vm-bootstap-bucket-{{ stackname }}"
        state: "present"
        region: "{{ region }}"
        #disable_rollback: true
        template: "../files/prerequest.yml"
        template_parameters:
          paBootstrapBucketname: "{{ pan_bootstrap }}"
        tags:
          Stack: "ansible-cloudformation"

    - name: upload pootstraping files to paBootstrapBucket 
      command: "aws s3 cp --recursive ../files/bootstrap  s3://{{ paBootstrapBucket }}"