AWSTemplateFormatVersion: 2010-09-09
Description: Blog application template
Resources:
  DemoAppEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-3bfab942
      KeyName: ec2key
      SecurityGroups: 
        - !Ref DemoAppSG
      UserData: !Base64 |
        #!/bin/bash
        yum install nginx -y
  DemoAppSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: access for web application
      SecurityGroupIngress: 
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
  DemoAppDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: blog
      Engine: MySQL
      EngineVersion: 5.5
      DBInstanceClass: "db.t2.micro"
      AllocatedStorage: 5
      MasterUsername: blog
      MasterUserPassword: blog1234
      DBSecurityGroups:
        - !Ref DemoAppDBSG
  DemoAppDBSG:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      GroupDescription: Access for db
      DBSecurityGroupIngress: 
        - EC2SecurityGroupId: sg-0129c97c
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 Instance
    Value: !Ref DemoAppEC2
  DBInstanceId:
    Description: InstanceId of the newly created RDS Instance
    Value: !Ref DemoAppDB